---
title: "area_calculations"
author: "Anna Calle"
date: "11/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
library(cowplot)
library(tidyverse)
```


```{r}
# Create vector with layer names
layer_name <- c("Depth", "Distance to Shore", "MPAs", "Artificial Reefs", "Reefs", "Wetlands", "No-take zones")

# Create vector with number of 0 cells in raster
freq_0 <- c(freq(depth_binary, value = 0), freq(dist_shore_binary, value = 0), freq(mpas_binary, value = 0), freq(reefs_artificial_binary, value = 0), freq(reefs_binary, value = 0), freq(wetlands_binary, value = 0), freq(no_take_binary, value = 0))

# Create df with layer names, frequency of 0 cells, and percentage of excluded area
area_df <- data.frame(layer_name, freq_0) %>% 
  mutate(percent_excluded = round(freq_0*100/30959, digits = 2)) %>% 
  arrange(percent_excluded) %>% 
   mutate( layer_name = factor(layer_name, levels = layer_name))

# Plot
area_col <- ggplot(area_df, aes(x = layer_name, y = percent_excluded)) +
  geom_col(fill = "darkturquoise") +
  coord_flip() +
  ylab("Percentage of EEZ Excluded") +
  xlab("") +
  scale_y_continuous( expand = c(0,0)) +
  theme_classic(14) +
  geom_text(
    aes(label = paste0(percent_excluded,"%"), y = percent_excluded + 15), 
    color = "black", 
    size = 5,
    hjust = 1
  ) 
 
area_col

```

