---
title: "cleaning_GBIF"
author: "Anna Calle"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


CLEANING GBIF DATA!
```{r}
# Load packages
library(tidyverse)
library(sf)
library(sp)
library(raster)
library(rgdal)
library(dplyr)
library(rgeos)
library(scales)
library(fasterize)
library(dismo)
library(maptools)
library(sdmpredictors) 
```

Download GBIF data
```{r}
# Get data directly from GBIF using 'gbif' function
# DON'T RUN!!! unless you really want to because there are more than 17,000 observations
cobia_gbif <- gbif("rachycentron", "canadum", geo = FALSE)

#Filter to just keep human observations:
human_cobia <- cobia_gbif %>% 
  filter(basisOfRecord == "HUMAN_OBSERVATION")


# How many rows and columns?
dim(cobia_gbif)

# Names of colums?
names(cobia_gbif)

# Keep only observations that have data (not NAs)
cobia_gbif <- subset(cobia_gbif, !is.na(lon) & !is.na(lat))

```


Make sure points are in the right location
```{r}
# Get world map data
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90,90), ylim=c(-70,70), axes=TRUE, col="light yellow")
# restore the box around the map
box()
# plot points
points(cobia_gbif$lon, cobia_gbif$lat, col='orange', pch=20, cex=0.75) > # plot points again to add a border, for better visibility
points(cobia_gbif$lon, cobia_gbif$lat, col='red', cex=0.75)

# Map doesn't show any incorrect pints on land
```

Look for coordinates of zero
```{r}
# The gbif function sets coordinates that are (0, 0) to NA, but not if only one coordinate is zero.
lonzero = subset(cobia_gbif, lon==0)
latzero = subset(cobia_gbif, lat==0)

# No coordinates of zero found
```

Eliminating duplicates
```{r}
dups <- duplicated(cobia_gbif[, c('lon', 'lat')])
# number of duplicates
sum(dups)
# keep only lat and lon of the records that are not duplicated 
cobia <- cobia_gbif[!dups, ] %>% 
  dplyr::select(lon, lat)

# Found 4401 duplicates
```

Create a SpatialPointsDataFrame for cobia
```{r}
coordinates(cobia) <- ~lon+lat
crs(cobia) <- crs(wrld_simpl)
class(cobia)
```

Sampling bias
```{r}
# create a RasterLayer with the extent of cobia data
r <- raster(cobia)
# set the resolution of the cells to (for example) 1 degree
res(r) <- 1
# expand (extend) the extent of the RasterLayer a little
r <- extend(r, extent(r)+1)
# sample:
cobia_sample <- gridSample(cobia, r, n=1)
# to illustrate the method and show the result
p <- rasterToPolygons(r)
plot(p, border='gray')
points(cobia)
# selected points in red
points(cobia_sample, cex=1, col='red', pch='x')
```

Save clean file
```{r}
# Save cobia sample as a csv
write.csv(cobia_sample, file = "cobia_sample.csv", row.names = FALSE)

```



