---
title: "cobia-range"
author: "Anna Calle"
date: "10/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load packages and read files
library(tidyverse)
library(sf)
library(raster)
library(rgdal)
library(dplyr)
library(rgeos)
library(scales)
library(fasterize)
library(dismo)
library(rJava)
library(maptools)
library(sdmpredictors) 

# This file is a a small subset of cobia occurrences (so that it doesn't take too long to load)
cobia <- read_csv("cobia_occurrences_BR.csv")


```

# Projection and Extent
```{r}
# set up projection parameter for use throughout script
projection <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

#set up extent parameter for use throughout script
ext <- extent(-180, 180, -90, 90)
```

# GBIF Data
```{r}
# Get data directly from GBIF using 'gbif' function
# DON'T RUN!!! unless you really want to use larger dataset because there are more than 17,000 observations
cobia_gbif <- gbif("rachycentron", "canadum", geo = FALSE)

# Get column names
names(cobia_gbif)

# Change cobia_data from small dataset to bigger dataset, keep only coordinates with a value
cobia_data <- cobia_gbif %>% 
  select("lon", "lat") %>% 
  filter("lon" != "NA")
```

# Map of cobia occurrences
```{r}
# Get world map data
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-80,70), ylim=c(-60,10), axes=TRUE, col="light yellow")
# restore the box around the map
box()
# plot points
points(cobia_data$lon, cobia_data$lat, col='orange', pch=20, cex=0.75) > # plot points again to add a border, for better visibility
points(cobia_data$lon, cobia_data$lat, col='red', cex=0.75)
```

# Presence data
```{r}
# Remove observations with no coordinates
cobia_data <- cobia %>% 
  dplyr::select( decimalLongitude,decimalLatitude) %>% 
filter(decimalLatitude != "NA")

colnames(cobia_data) <- c("lon", "lat")

summary(cobia_data)

cobia_data <- as.data.frame(cobia_data)
```

# Environmental variables
```{r}
# Explore datasets in the package 
list_datasets() 

# Explore layers in a dataset 
list_layers() 

# Download specific layers to current directory. In this case we are downloading mean sea surface temperature, max sea surface temperature, min sea surface temperature, dissolved oxygen, and sea surface salinity
files <- load_layers(c("BO_sstmean", "BO_sstmax", "BO_sstmin", "BO_dissox", "MS_biogeo08_sss_mean_5m")) 

# Make a rasterLayer with predictor variables
predictors <- stack(files)

```
# Maxent requirements 
```{r}
# Before running maxent using the 'dismo' package:
# - download maxent program from http://www.cs.princeton.edu/~schapire/maxent/
# -  Put the file ’maxent.jar’ in the ’java’ folder of the ’dismo’ package. That is the folder returned by system.file("java", package="dismo")

```


# Maxent
```{r}
# Run Maxent if java file is in the correct folder

jar <- paste(system.file(package="dismo"), "/java/maxent.jar", sep='')

if (file.exists(jar)) {
  # Fit maxent model
  cobia_model <- maxent(predictors, p = cobia_data)
  
 # Plot showing importance of every variable
 plot(cobia_model)
 
 # Response curves
 response(cobia_model)
 
 # Predict the entire dataset
 cobia_pred <- predict(cobia_model, predictors)
 
 # Plot predictions
 plot(cobia_pred, main = "Predicted Suitability")
 map('worldCobia', fill=FALSE, add=TRUE)
points(cobia_data$lon, cobia_data$lat, pch="+", cex=0.2)

} else {
  cat('cannot run this example because maxent is not available') + plot(1)
}

```
```{r}
map('worldHires', fill=FALSE, add=TRUE)
```


