---
title: "dist_shore"
author: "Anna Calle"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
library(rnaturalearth)
library(beepr)
```

```{r}
#import the limits of Brazil #110, 50, or 10 metters for scale (resolution)
bound_BRA <- ne_countries(scale = 110, country = "Brazil", returnclass = "sf")%>% 
  sf::st_crop(eez_BRA)


#plot
plot(bound_BRA)
```


```{r}
# crop, reproject, mask

# a sf object with st_transform()
# a Spatial* object with spTransform()
# a raster object with projectRaster()

# GMED for wave height

# distance function --> calculate distance to nearest non NA cell
# empty raster with certain extent and resolution
# rasterize coastline
# st_buffer
# area function



# export as tiff for qgis

extent<-extent(eez_BRA)
res = res(min_sst_BRA)

```

```{r}
# Create empty raster

r <- raster( extent, resolution = res)

# Rasterize coastline
r2 <- rasterize(bound_BRA, r, 1)

# plot
plot(r2)

# Calculate distance to nearest non-NA pixel
d <- distance(r2)
beep()

# Export the raster
writeRaster(x = d, filename = paste0(path,"/dist_shore.tif"), overwrite = F)

plot(d)


# Make land NAs


```


