---
title: "sst_range"
author: "Anna Calle"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
library(tidyverse)
library(sf)
library(raster)
library(rgdal)
library(dplyr)
library(rgeos)
library(scales)
library(fasterize)
library(dismo)
library(rJava)
library(maptools)
library(sdmpredictors)
library(maps)
library(sp)
library(ncdf4)
```

*Cobia's optimal growth is 27-29 C

Objectives:
- Keep locations with min temperature higher than 27C
- Keep locations with max temperature lower than 29C

Download sst from Bio-Oracle
```{r}
# Explore datasets in the package 
list_datasets() 

# Explore layers in a dataset 
list_layers() 

# Download max and min sst layers
min <- load_layers("BO_sstmin")
max <- load_layers("BO_sstmax")
```
Visualize data
```{r}
# Histograms
hist(min)
hist(max)

# Plots
plot(min)
plot(max)
```

Reclassify min sst layer
```{r}
# Reclassify matrix
rcl_matrix_min <- c( -Inf, 27, 0,
                27, Inf, 1)

# Reclassify sst
sst_binary_min <- reclassify(min, rcl = rcl_matrix_min)

# Plot reclassified layer
plot(sst_binary_min)
```
Reclassify max sst layer
```{r}
# Reclassify matrix
rcl_matrix_max <- c( -Inf, 29, 1,
                29, Inf, 0)

# Reclassify sst
sst_binary_max <- reclassify(min, rcl = rcl_matrix_max)

# Plot reclassified layer
plot(sst_binary_max)
```

SST range
```{r}
# Overlay min and max binary layers to get range
sst_range <- overlay(sst_binary_min, sst_binary_max, fun = function(x,y){x+y})

# Plot range
plot(sst_range)

```

Brazil's EEZ
```{r}
# Read file
eez <- st_read(dsn = ".", layer = "eez")

# View column names
head(eez)

# Plot
ggplot() + geom_sf(data = eez)
```


Mask and crop 
```{r}
# Create mask of sst range using ezz boundaries
masked <- mask(x = sst_range, mask =eez)
plot(masked)

# Crop sst range to Brazil's EEZ extent
cropped <- crop(x = masked, y = extent(eez))
plot(cropped)
# Add basemap (Note: borders don't match)
map('world', fill = T, add = T, col = 'gray')
```

Reefs
```{r}
# Read shapefile
reefs <-  read_sf(dsn = ".", layer = "reef_500_poly")
plot(reefs)
  
```

Mask using reefs
```{r}
reefs_masked <- mask(x = sst_range, mask =reefs)
plot(reefs_masked)
```



Reading depth netcdf file
```{r}




```





